//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro.Viracor.Labalert.Mobile.Main.Bro.Resources.Locators.Cms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContestsLocators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestsLocators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Euro.Viracor.Labalert.Mobile.Main.Bro.Resources.Locators.Cms.ContestsLocators", typeof(ContestsLocators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id__btnSaveClose.
        /// </summary>
        internal static string BtnSaveClose {
            get {
                return ResourceManager.GetString("BtnSaveClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__div[class=&apos;ui-pnotify-text&apos;].
        /// </summary>
        internal static string InfoPopup {
            get {
                return ResourceManager.GetString("InfoPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__table#contestGrid.
        /// </summary>
        internal static string TblContests {
            get {
                return ResourceManager.GetString("TblContests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__table#contestGrid tr.
        /// </summary>
        internal static string TblContestsRows {
            get {
                return ResourceManager.GetString("TblContestsRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__div[class*=&apos;cm-s-monokai&apos;].
        /// </summary>
        internal static string TxtAreaContests {
            get {
                return ResourceManager.GetString("TxtAreaContests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id__gs_Id.
        /// </summary>
        internal static string TxtContestsId {
            get {
                return ResourceManager.GetString("TxtContestsId", resourceCulture);
            }
        }
    }
}
