//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro.Viracor.Labalert.Mobile.Main.Bro.Resources.Locators.Cms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddMessageLocators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddMessageLocators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Euro.Viracor.Labalert.Mobile.Main.Bro.Resources.Locators.Cms.AddMessageLocators", typeof(AddMessageLocators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id__btnSaveSend.
        /// </summary>
        public static string BtnSaveSend {
            get {
                return ResourceManager.GetString("BtnSaveSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id__MessageType.
        /// </summary>
        public static string CboMessageType {
            get {
                return ResourceManager.GetString("CboMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__label[for=&quot;allAgents&quot;].
        /// </summary>
        public static string ChkAllAgents {
            get {
                return ResourceManager.GetString("ChkAllAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__label[for=&quot;allDistributors&quot;].
        /// </summary>
        public static string ChkAllDistributors {
            get {
                return ResourceManager.GetString("ChkAllDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__label[for=&quot;allRetailers&quot;].
        /// </summary>
        public static string ChkAllRetailers {
            get {
                return ResourceManager.GetString("ChkAllRetailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__label[for=&quot;allSales&quot;].
        /// </summary>
        public static string ChkAllSalespeople {
            get {
                return ResourceManager.GetString("ChkAllSalespeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__label[for=&quot;IsImportant&quot;].
        /// </summary>
        public static string ChkImportant {
            get {
                return ResourceManager.GetString("ChkImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__label[for=&quot;IsPopup&quot;].
        /// </summary>
        public static string ChkPopup {
            get {
                return ResourceManager.GetString("ChkPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__[class=&apos;select2-results__option select2-results__option--highlighted&apos;].
        /// </summary>
        public static string LiRetailerOptionDisplayed {
            get {
                return ResourceManager.GetString("LiRetailerOptionDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__[class=&apos;select2-selection__choice&apos;].
        /// </summary>
        public static string LiSelectedRetailer {
            get {
                return ResourceManager.GetString("LiSelectedRetailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__div[class*=&quot;panel-body&quot;].
        /// </summary>
        public static string TxtPanel {
            get {
                return ResourceManager.GetString("TxtPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__#selectRetailers+span input.
        /// </summary>
        public static string TxtSearchRetailerPin {
            get {
                return ResourceManager.GetString("TxtSearchRetailerPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id__Subject.
        /// </summary>
        public static string TxtSubject {
            get {
                return ResourceManager.GetString("TxtSubject", resourceCulture);
            }
        }
    }
}
