//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro.Viracor.Labalert.Mobile.Main.Bro.Resources.Locators.Cms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChangeSetsLocators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChangeSetsLocators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Euro.Viracor.Labalert.Mobile.Main.Bro.Resources.Locators.Cms.ChangeSetsLocators", typeof(ChangeSetsLocators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__a[href*=&apos;Changeset/PreviewChangeset&apos;].
        /// </summary>
        internal static string BtnPreview {
            get {
                return ResourceManager.GetString("BtnPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath__//table[@id=&apos;changesetGrid&apos;]//tr[position() &gt; 1].
        /// </summary>
        internal static string ChangesetRows {
            get {
                return ResourceManager.GetString("ChangesetRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id__jqGridFilter_changesetGrid_ChangesetState_eq.
        /// </summary>
        internal static string DdlStatusFilter {
            get {
                return ResourceManager.GetString("DdlStatusFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id__jqGridFilter_changesetGrid_Id_eq-error.
        /// </summary>
        internal static string LblIdError {
            get {
                return ResourceManager.GetString("LblIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id__jqGridFilter_changesetGrid_Id_eq.
        /// </summary>
        internal static string TxtId {
            get {
                return ResourceManager.GetString("TxtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id__changesetGrid_pager_right.
        /// </summary>
        internal static string TxtNumberEntries {
            get {
                return ResourceManager.GetString("TxtNumberEntries", resourceCulture);
            }
        }
    }
}
