//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro.Viracor.Labalert.Mobile.Main.Viracor.Resources.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_Bro_english {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_Bro_english() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Euro.Viracor.Labalert.Mobile.Main.Viracor.Resources.I18n.Language_Bro_english", typeof(Language_Bro_english).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        internal static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed For Customers.
        /// </summary>
        internal static string AllowedForCustomers {
            get {
                return ResourceManager.GetString("AllowedForCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed For Distributors.
        /// </summary>
        internal static string AllowedForDistributors {
            get {
                return ResourceManager.GetString("AllowedForDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed For Retailers.
        /// </summary>
        internal static string AllowedForRetailers {
            get {
                return ResourceManager.GetString("AllowedForRetailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set allowed for retailers while not allowed for distributors.
        /// </summary>
        internal static string CanNotSetAllowedForRetailersWhileNotAllowedForDistributors {
            get {
                return ResourceManager.GetString("CanNotSetAllowedForRetailersWhileNotAllowedForDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Beta Testers.
        /// </summary>
        internal static string ClearAllBetaTesters {
            get {
                return ResourceManager.GetString("ClearAllBetaTesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will delete the Product with all its Product Items. You cannot undo the action! Are you sure you want to delete this item?.
        /// </summary>
        internal static string DeleteProductPopupMessage {
            get {
                return ResourceManager.GetString("DeleteProductPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor Id should be a number.
        /// </summary>
        internal static string DistributorIdShouldBeANumber {
            get {
                return ResourceManager.GetString("DistributorIdShouldBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was edited successfully..
        /// </summary>
        internal static string EditedSucessfull {
            get {
                return ResourceManager.GetString("EditedSucessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Item ID.
        /// </summary>
        internal static string InventoryItemID {
            get {
                return ResourceManager.GetString("InventoryItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitations have been placed on your wallet. Please contact customer service at 1-877-509-7998.
        /// </summary>
        internal static string LimitationsHaveBeenPlacedOnYourWalletPleaseContactCustomerServiceAt18775097998 {
            get {
                return ResourceManager.GetString("LimitationsHaveBeenPlacedOnYourWalletPleaseContactCustomerServiceAt18775097998", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Amount.
        /// </summary>
        internal static string MaxAmount {
            get {
                return ResourceManager.GetString("MaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Retailer Commission should be greater than or equal to Retailer Commission.
        /// </summary>
        internal static string MaxRetailerCommissionShouldBeGreaterThanOrEqualToRetailerCommission {
            get {
                return ResourceManager.GetString("MaxRetailerCommissionShouldBeGreaterThanOrEqualToRetailerCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message \d{4} was sent successfully..
        /// </summary>
        internal static string MessageWasSentSuccessfully {
            get {
                return ResourceManager.GetString("MessageWasSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Amount.
        /// </summary>
        internal static string MinAmount {
            get {
                return ResourceManager.GetString("MinAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Transaction # {0}.
        /// </summary>
        internal static string MoneyTransferCancelledSuccessPopupMessage {
            get {
                return ResourceManager.GetString("MoneyTransferCancelledSuccessPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered list.
        /// </summary>
        internal static string OrderedList {
            get {
                return ResourceManager.GetString("OrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully!.
        /// </summary>
        internal static string PasswordHasBeenResetSuccessfully {
            get {
                return ResourceManager.GetString("PasswordHasBeenResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranges can not overlap for the same payer, delivery method and payment method.
        /// </summary>
        internal static string PricingGroupItemErrorMessage {
            get {
                return ResourceManager.GetString("PricingGroupItemErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id.
        /// </summary>
        internal static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Item status was set to &quot;DISCONTINUED&quot;. Retailers won&apos;t be able to sell this item but it will be visible for reporting purposes..
        /// </summary>
        internal static string ProductItemStatusWasSetToDiscontinued {
            get {
                return ResourceManager.GetString("ProductItemStatusWasSetToDiscontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Item was created successfully..
        /// </summary>
        internal static string ProductItemWasCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ProductItemWasCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Item was deactivated successfully..
        /// </summary>
        internal static string ProductItemWasDeactivatedSuccessfully {
            get {
                return ResourceManager.GetString("ProductItemWasDeactivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product metadata updated successfully.
        /// </summary>
        internal static string ProductMetadataUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ProductMetadataUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product notes updated successfully.
        /// </summary>
        internal static string ProductNotesUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ProductNotesUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product was activated successfully..
        /// </summary>
        internal static string ProductWasActivatedSuccessfully {
            get {
                return ResourceManager.GetString("ProductWasActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0} was created successfully. Please continue setup by adding Product Item(s) and defining Commissions / Fees.
        /// </summary>
        internal static string ProductWasCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ProductWasCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0} was created successfully. Please continue setup by adding Product Item(s) and defining Commissions / Fees.
        /// </summary>
        internal static string ProductWasCreatedSuccessfullyPleaseContinueSetupByAddingProductItemAndDefiningCommissionsFees {
            get {
                return ResourceManager.GetString("ProductWasCreatedSuccessfullyPleaseContinueSetupByAddingProductItemAndDefiningCom" +
                        "missionsFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile was successfully updated.
        /// </summary>
        internal static string ProfileWasSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("ProfileWasSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer Commission should be between Min and Max Retailer Commission values.
        /// </summary>
        internal static string RetailerCommissionShouldBeBetweenMinAndMaxRetailerCommissionValues {
            get {
                return ResourceManager.GetString("RetailerCommissionShouldBeBetweenMinAndMaxRetailerCommissionValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notes.
        /// </summary>
        internal static string ShowNotes {
            get {
                return ResourceManager.GetString("ShowNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test_1234 profile was created successfully.
        /// </summary>
        internal static string Test1234ProfileWasCreatedSuccessfully {
            get {
                return ResourceManager.GetString("Test1234ProfileWasCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile was deleted..
        /// </summary>
        internal static string TheProfileWasDeleted {
            get {
                return ResourceManager.GetString("TheProfileWasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unordered list.
        /// </summary>
        internal static string UnorderedList {
            get {
                return ResourceManager.GetString("UnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload retailer black list for product.
        /// </summary>
        internal static string UploadRetailerBlackListForProduct {
            get {
                return ResourceManager.GetString("UploadRetailerBlackListForProduct", resourceCulture);
            }
        }
    }
}
