//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDT.OneApp.Main.Bro.Resources.CommonLocators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonLocators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonLocators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDT.OneApp.Main.Bro.Resources.CommonLocators.CommonLocators", typeof(CommonLocators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath__//button[@id=&apos;btn-addProfile&apos;].
        /// </summary>
        public static string BtnCreateNewProfile {
            get {
                return ResourceManager.GetString("BtnCreateNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath__//button[@id=&apos;btn-deleteProfile&apos;].
        /// </summary>
        public static string BtnDeleteProfile {
            get {
                return ResourceManager.GetString("BtnDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath__//button[@id=&apos;btn-editProfile&apos;].
        /// </summary>
        public static string BtnRenameProfile {
            get {
                return ResourceManager.GetString("BtnRenameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__[class=&apos;btn btn-default btn-xs&apos;][type=&apos;submit&apos;].
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath__//select[@id=&apos;SelectedProfile&apos;].
        /// </summary>
        public static string DdlProfileName {
            get {
                return ResourceManager.GetString("DdlProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__div.header-breadcrumbs &gt; a.
        /// </summary>
        public static string LblPageTitle {
            get {
                return ResourceManager.GetString("LblPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath__//span[@class=&apos;ui-jqgrid-title&apos;].
        /// </summary>
        public static string LblProfileComissions {
            get {
                return ResourceManager.GetString("LblProfileComissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath__//a[@href=&apos;/us/ProfileManagement/Index&apos; and contains(@class,&apos;btn&apos;)].
        /// </summary>
        public static string LblProfiles {
            get {
                return ResourceManager.GetString("LblProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath__//span[@id=&apos;select2-SelectedProfile-container&apos;].
        /// </summary>
        public static string LblSelectedProfileName {
            get {
                return ResourceManager.GetString("LblSelectedProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xpath__//div[@class=&apos;ui-pnotify-text&apos;].
        /// </summary>
        public static string LblSuccessNotification {
            get {
                return ResourceManager.GetString("LblSuccessNotification", resourceCulture);
            }
        }
    }
}
