//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro.Viracor.Labalert.Mobile.Main.Bro.Resources.Locators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BossRevolutionOrganizerLocators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BossRevolutionOrganizerLocators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Euro.Viracor.Labalert.Mobile.Main.Bro.Resources.Locators.BossRevolutionOrganizerL" +
                            "ocators", typeof(BossRevolutionOrganizerLocators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__div[id=&apos;loading&apos;][style*=&apos;display: none&apos;].
        /// </summary>
        public static string AlertLoadingDisplayNone {
            get {
                return ResourceManager.GetString("AlertLoadingDisplayNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__[class=&apos;ajax-loading&apos;] span.
        /// </summary>
        public static string IcnLoading {
            get {
                return ResourceManager.GetString("IcnLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__div[class*=&apos;header-&apos;] a[href*=&apos;/Home/Index&apos;].
        /// </summary>
        public static string LnkBossRevolutionOrganizerTitle {
            get {
                return ResourceManager.GetString("LnkBossRevolutionOrganizerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__a[href*=&apos;RetailerManagement/Index&apos;][class*=&apos;btn&apos;].
        /// </summary>
        public static string LnkRetailers {
            get {
                return ResourceManager.GetString("LnkRetailers", resourceCulture);
            }
        }
    }
}
