//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro.Viracor.Labalert.Mobile.Main.Bro.Resources.Locators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BROSideBarMenuLocators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BROSideBarMenuLocators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Euro.Viracor.Labalert.Mobile.Main.Bro.Resources.Locators.BROSideBarMenuLocators", typeof(BROSideBarMenuLocators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__li[title=&apos;About&apos;].
        /// </summary>
        public static string LblAbout {
            get {
                return ResourceManager.GetString("LblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__li[title=&apos;Cms&apos;].
        /// </summary>
        public static string LblCms {
            get {
                return ResourceManager.GetString("LblCms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__li[title=&apos;Configuration&apos;].
        /// </summary>
        public static string LblConfiguration {
            get {
                return ResourceManager.GetString("LblConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__li[title=&apos;Dashboard&apos;].
        /// </summary>
        public static string LblDashboard {
            get {
                return ResourceManager.GetString("LblDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__li[title=&apos;Distributors&apos;].
        /// </summary>
        public static string LblDistributors {
            get {
                return ResourceManager.GetString("LblDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__li[title=&apos;Money Transfer&apos;].
        /// </summary>
        public static string LblMoneyTransfer {
            get {
                return ResourceManager.GetString("LblMoneyTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__li[title=&apos;Products&apos;].
        /// </summary>
        public static string LblProducts {
            get {
                return ResourceManager.GetString("LblProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__li[title=&apos;Profiles&apos;].
        /// </summary>
        public static string LblProfiles {
            get {
                return ResourceManager.GetString("LblProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__li[title=&apos;Reports&apos;].
        /// </summary>
        public static string LblReports {
            get {
                return ResourceManager.GetString("LblReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css__li[title=&apos;Customers&apos;].
        /// </summary>
        public static string LblRetailers {
            get {
                return ResourceManager.GetString("LblRetailers", resourceCulture);
            }
        }
    }
}
