//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro.Viracor.Labalert.Mobile.Main.Bro.Resources.Locators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BroUrls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BroUrls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Euro.Viracor.Labalert.Mobile.Main.Bro.Resources.Locators.BroUrls", typeof(BroUrls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoneyTransfer/BuyRates.
        /// </summary>
        public static string BuyRates {
            get {
                return ResourceManager.GetString("BuyRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerManagement/CustomerMoneyTransfer.
        /// </summary>
        public static string CustomersMoneyTransfer {
            get {
                return ResourceManager.GetString("CustomersMoneyTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerManagement/CustomerMoneyTransferV1.
        /// </summary>
        public static string CustomersMoneyTransferV1 {
            get {
                return ResourceManager.GetString("CustomersMoneyTransferV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home/Index.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor/Index.
        /// </summary>
        public static string Distributors {
            get {
                return ResourceManager.GetString("Distributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoneyTransfer/PricingGroup/Index.
        /// </summary>
        public static string PricingGroup {
            get {
                return ResourceManager.GetString("PricingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoneyTransfer/RateGroup/Index.
        /// </summary>
        public static string RateGroup {
            get {
                return ResourceManager.GetString("RateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report/BillPay.
        /// </summary>
        public static string ReportBillPay {
            get {
                return ResourceManager.GetString("ReportBillPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetailerManagement/Index.
        /// </summary>
        public static string Retailers {
            get {
                return ResourceManager.GetString("Retailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetailerManagement/ManageStores/{0}.
        /// </summary>
        public static string RetailersManageStore {
            get {
                return ResourceManager.GetString("RetailersManageStore", resourceCulture);
            }
        }
    }
}
